blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/seaguntech/seaguntech-monorepo-template/security/advisories/new
    about: Please report security issues here.
  - name: Documentation
    url: https://github.com/seaguntech/seaguntech-monorepo-template/wiki
    about: Check the docs before filing.
